### ISSUE TITLE
Unfriendly error when the Java code does not compile

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-java#540] opened 2022-05-04 13:56 UTC
### What happened?

When there is a Java compilation error, we get a poor experience in how it is reported as the plugin discovery step fails. 

### Steps to reproduce

Introduce a compilation error into a working Java project, run `pulumi preview`.

### Expected Behavior

Pulumi reports compilation error in the user program.

### Actual Behavior

Pulumi reports `error: failed to discover plugin requirements: language host could not determine Pulumi packages: language host counld not run plugin discovery command successfully`

```[nix-shell:~/pulumi-java/tests/examples/azure-java-static-website]$ pulumi preview
Previewing update (dev)

View Live: https://app.pulumi.com/t0yv0/azure-java-static-website/dev/previews/8399198f-5416-4c9a-9729-ca49e6691b7c

     Type                 Name                           Plan     Info
     pulumi:pulumi:Stack  azure-java-static-website-dev           14 messages
 
Diagnostics:
  pulumi:pulumi:Stack (azure-java-static-website-dev):
    /Users/anton/pulumi-java/tests/examples/azure-java-static-website/app/src/main/java/staticwebsite/App.java:1: error: reached end of file while parsing
    BAM
    ^
    1 error
    FAILURE: Build failed with an exception.
    * What went wrong:
    Execution failed for task ':app:compileJava'.
    > Compilation failed; see the compiler error output for details.
    * Try:
    > Run with --stacktrace option to get the stack trace.
    > Run with --info or --debug option to get more log output.
    > Run with --scan to get full insights.
    * Get more help at https://help.gradle.org
    BUILD FAILED in 3s
 
warning: A new version of Pulumi is available. To upgrade from version '3.30.0' to '3.31.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
error: failed to discover plugin requirements: language host could not determine Pulumi packages: language host counld not run plugin discovery command successfully: './gradlew ./gradlew -q run --console=plain -PmainClass=com.pulumi.bootstrap.internal.Main --args=packages' exited with non-zero exit code: 1
```

### Versions used

pulumi-language-java 0.1.0
com.pulumi.pulumi 0.1.0
pulumi cli v3.30.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pawelprazak** [comment] 2022-05-04 14:04
Related to or a duplicate of #538

**Closed** 2022-05-17 09:07 UTC
Labels: impact/usability, kind/bug, size/S
